CREATE TABLE IF NOT EXISTS planting_years (
  planting_year    INTEGER NOT NULL,
  date_created     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  date_modified    TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,

  PRIMARY KEY ( planting_year )
);
